### ISSUE TITLE
Wrong description

### ISSUE THREAD

**Issue by Lmmb74** [Simonsator/Friends-MSG-Toggle#1]
https://github.com/Simonsator/Friends-MSG-Toggle/blob/a36a6e8c605d0ca798bc78eccefa99ce45576ce3/src/main/resources/plugin.yml#L6

Welp, same as https://github.com/Simonsator/Party-Toggle/issues/1 I guess.

**Comment by Simonsator** [comment]
Fixed with https://github.com/Simonsator/Friends-MSG-Toggle/commit/2347db6296d745711373d326c4ce6ce908df4a96
